### ISSUE TITLE
waf based builds

### ISSUE THREAD

**Issue by Kelly-Foster** [Microsoft/Frigatebird#4]
What can I do to help flush out waf build issues?  Running Ubuntu / WSL on Windows 10 laptop, and everything of late in ArduPlane / ArduCopter is waf based.  It's a bit of a step backwards in this ecosystem to have to use make.  Also, hoping to fly Frigatebird code on latest ArduPlane master running on ChibiOS HAL on Matek F405-Wing, on Radian Pro.  So a highly relevant config, IMHO.  Would *really* like to avoid having to maintain parallel and different build environments/flows.

Kelly

**Comment by samuelctabor** [comment]
Hi Kelly,

I've started to produce a clean implementation on top of ArduPlane 3.8.2 with a view to rebasing on master when tested. For now I'm removing most of the non-POMPD features to keep the changes minimal.

https://github.com/samuelctabor/ardupilot/pull/1/files

The waf build process works fine for me on Ubuntu with this code, I think Windows was the issue.

Sam

**Comment by akolobov** [comment]
Hi Kelly, 


Indeed, the issue is that waf -- even for vanilla ArduPlane master -- doesn't work for us on Windows 10 for the px4-v2 platform, as Sam guessed. Waf does work for ArduPlane SITL even on Windows though, and based on that we see that it's much faster and more reliable than Make. If only it worked on Windows 10 for px4-v2 and other platforms we'd switch to it in no time.

In terms of help: could you tell us whether ArduPlane builds fine for you on Windows 10 for px4-v2 (not the Linux subsystem, but natively)? If not, what errors are you getting?

Thanks,


Andrey

**Comment by Kelly-Foster** [comment]
Andrey,

I have only two working build environments at the moment. Ubuntu under WSL, and a native Linux install on my Raspberry Pi 2. I have not been building anything native under Windows. The interoperation between Windows functions and WSL-based builds has been great to date for me.   I would prefer to continue on the Ubuntu/WSL path for now.

Kelly

**Comment by akolobov** [comment]
As part of merging in ArduPlane changes up to version 3.9.3, I've fixed this. Now waf if the primary way of building Frigatebird.
