### ISSUE TITLE
PR the SilentWings SITL backend for ArduPilot master

### ISSUE THREAD

**Issue by tridge** [Microsoft/Frigatebird#7]
hi guys, are you interested in bringing the SilentWings SITL backend into ardupilot master? I'd be happy to look at a PR for that, or I could just copy what you've done.
I haven't tried silent wings myself yet, but I just saw the video from Marco. Looks really nice.

**Comment by robustini** [comment]
Thanks @tridge  for opening this issue, here is one of my tlog showing the problem of bad AHRS with Mission Planner and SITL, using X-Plane 11.
I built SITL from this branch of @samuelctabor, where we made some upgrades and fix to the SOAR for Ardupilot:

https://github.com/samuelctabor/ardupilot/commits/SoaringUpgrades


[2019-06-08 10-42-29.zip](https://github.com/microsoft/Frigatebird/files/3280196/2019-06-08.10-42-29.zip)

**Comment by akolobov** [comment]
@tridge: Sure! I'm travelling right now and should be able to prepare the PR in ~a week. Feel free to do it in the meantime if you like, otherwise I'll do it when I get back.

@robustini: Thanks a lot for testing out the SilentWings SITL! Indeed, we have been seeing "Bad AHRS" as well, and after a short investigation I still don't understand what causes it. Since you are seeing it with X-Plane as well, apparently it's not specific to the SilentWings SITL though.

**Comment by tridge** [comment]
I think the issue is you have zero offsets for the accels, so it thinks it is uncalibrated. Try setting INS_ACCOFFS_X=0.001 and so on for the others.
or we could change master so it doesn't set AHRS unhealthy on zero accel offsets if EKF type is 10

**Comment by akolobov** [comment]
Ohhh I see! Best to change it in master then, since the issue crops up in other SITLs too. Let me test it out first though.

**Comment by magicrub** [comment]
Why isn't this repo a fork? It would be a lot easier for ArduPilot developers to contribute to

**Comment by robustini** [comment]
@akolobov, no news about that?

**Comment by robustini** [comment]
> 
> 
> I think the issue is you have zero offsets for the accels, so it thinks it is uncalibrated. Try setting INS_ACCOFFS_X=0.001 and so on for the others.
> or we could change master so it doesn't set AHRS unhealthy on zero accel offsets if EKF type is 10

@tridge i tried, but it does not solve the problem.
And anyway the BAD AHRS also gives it on the GPS.

**Comment by akolobov** [comment]
@tridge, @robustini: please take a look at the ArduPilot PR for this change: https://github.com/ArduPilot/ardupilot/pull/11641

@robustini: The PR fixes the BAD AHRS issue, although a bit differently than how @tridge suggested. "Bad GPS Health" still crops up sometimes though. I suspect this is because of excessive jitter in GPS data timing. @tridge, does it make sense to relax requirements on GPS's data rate variance in SITL?

**Comment by tridge** [comment]
we should only relax the checks if AHRS_EKF_TYPE is 10. We rely on having all the checks active for normal SITL in order to test them.

**Comment by robustini** [comment]
> 
> 
> @tridge, @robustini: please take a look at the ArduPilot PR for this change: [ArduPilot/ardupilot#11641](https://github.com/ArduPilot/ardupilot/pull/11641)
> 
> @robustini: The PR fixes the BAD AHRS issue, although a bit differently than how @tridge suggested. "Bad GPS Health" still crops up sometimes though. I suspect this is because of excessive jitter in GPS data timing. @tridge, does it make sense to relax requirements on GPS's data rate variance in SITL?

Too many unnecessary implementations, @tridge  has already solved this and it works, tested.

https://github.com/ArduPilot/ardupilot/pull/11634

**Comment by magicrub** [comment]
@akolobov great work, thanks for jumping on this! We're excited to see this great work get merged back into upstream

**Comment by akolobov** [comment]
Done in the summer, closing.
