### ISSUE TITLE
Code is missing attributation to Stack Overflow Q&A

### ISSUE THREAD

**Issue by gnif** [Microsoft/Frigatebird#8]
The code at https://github.com/microsoft/Frigatebird/blob/master/libraries/AP_HAL_F4Light/hardware/sd/Sd2Card.cpp#L82-L138 has been lifted from my answer at stack overflow.

https://stackoverflow.com/questions/21593692/convert-unix-timestamp-to-date-without-system-libs

`user contributions licensed under cc by-sa 4.0 with attribution required.`

https://creativecommons.org/licenses/by-sa/4.0/

**Comment by peterbarker** [comment]
@gnif apologies for any slight there.  That HAL was a whole lot of code that made its way into ArduPilot with less than the usual amount of checking that we do.  The FrigateBird project forked the ArduPilot project, and didn't add that code.

That HAL was removed from ArduPilot in January 2019, so as far as I'm aware we don't have any code left in there in contravention of your license.  Do please let us know with an issue on the ArduPilot repository if that is incorrect.

The equivalent code in ArduPilot can be found here:  https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.c#L141 - as you can see from the comment it has a rather different lineage!

@gnif is it OK if this issue is closed?

**Comment by gnif** [comment]
Hi,

Looking at the last work on this project, it's clearly no longer used and I have no issue with the code remaining untouched. Feel free to close this as resolved, thanks for getting in touch.
